server.port=8082

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================
# Hyperledger Fabric Config
# =========================
fabric.connection.profile=fabric-config/connection-org1.json
fabric.channel.name=mychannel
fabric.contract.name=fingerprint

# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.com.fingerprint=DEBUG
logging.level.org.hyperledger.fabric=INFO