server.port=8082

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================
# FABRIC CONFIG (FINAL FIX)
# =========================
fabric.connection.profile=/app/fabric-config/connection-org1.json
fabric.wallet.path=/app/wallet
fabric.identity=User1
fabric.channel.name=mychannel
fabric.contract.name=fingerprint

logging.level.root=INFO
logging.level.com.fingerprint=DEBUG